name: Generate Ascii

on : push 

jobs:
  ascii-job:
    runs-on: ubuntu-latest
    steps:
    - name: checkuot repo
      uses: actions/checkout@v4

    - name: Execute shell scritpt
      run: ./ascii-script.sh
       
      

    